common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *common
  database: bloccit_development

test:
  <<: *common
  database: bloccit_test

production:
  <<: *common
  database: bloccit_production